name: metricbeat

logging.level: debug

metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      templates:
        - config:
            - module: docker
              metricsets:
                - container
                - cpu
                - memory
                - network
              period: 10s
              hosts: ['unix:///var/run/docker.sock']

processors:
  - add_cloud_metadata: ~
  - add_fields:
      target: service
      fields:
        name: orchestrapay-container

output.elasticsearch:
  hosts: ['15.204.140.103:9200']
  username: metricbeat_internal
  password: ${METRICBEAT_INTERNAL_PASSWORD:-M3tricB3@t!2024}

http:
  enabled: true
  host: 0.0.0.0
